import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import http from 'node:http';
import { stagedPost, sha256, parseArgs } from '../scripts/post-wp-draft.mjs';

function fixture(){const root=fs.mkdtempSync(path.join(os.tmpdir(),'wpdraft-')); fs.mkdirSync(path.join(root,'articles','demo'),{recursive:true}); const html='<h2>Demo Title</h2><p>Body text long enough</p>'; fs.writeFileSync(path.join(root,'articles','demo','article.html'),html); fs.writeFileSync(path.join(root,'articles','demo','metadata.json'),JSON.stringify({title:'Demo Title',slug:'demo'},null,2)); return {root,html}}
async function server(handler){const s=http.createServer(async(req,res)=>{let b=''; for await (const c of req)b+=c; handler(req,res,b)}); await new Promise(r=>s.listen(0,'127.0.0.1',r)); return {url:`http://127.0.0.1:${s.address().port}`, close:()=>new Promise(r=>s.close(r))}}
function json(res,obj){res.setHeader('content-type','application/json'); res.end(JSON.stringify(obj))}

test('creates minimal draft, updates content only, verifies draft and writes metadata', async()=>{const {root,html}=fixture(); const calls=[]; let post={id:101,slug:'demo',status:'draft',title:{raw:'Demo Title'},content:{raw:''},link:'http://wp/?p=101'}; const srv=await server((req,res,body)=>{calls.push({url:req.url,method:req.method,body:body&&JSON.parse(body)}); if(req.url.startsWith('/wp-json/wp/v2/users/me')) return json(res,{id:1}); if(req.url.startsWith('/wp-json/wp/v2/posts?')) return json(res,[]); if(req.url==='/wp-json/wp/v2/posts'&&req.method==='POST'){post.content.raw=JSON.parse(body).content; return json(res,post)} if(req.url==='/wp-json/wp/v2/posts/101'&&req.method==='POST'){assert.deepEqual(Object.keys(JSON.parse(body)),['content']); post.content.raw=JSON.parse(body).content; return json(res,post)} if(req.url==='/wp-json/wp/v2/posts/101?context=edit') return json(res,post); res.statusCode=404; json(res,{})}); try{const r=await stagedPost({slug:'demo',root,baseUrl:srv.url,username:'u',password:'p'}); assert.equal(r.postId,101); assert.equal(calls.find(c=>c.url==='/wp-json/wp/v2/posts').body.status,'draft'); assert.match(calls.find(c=>c.url==='/wp-json/wp/v2/posts').body.content,/codex-staged-draft/); const meta=JSON.parse(fs.readFileSync(path.join(root,'articles','demo','metadata.json'))); assert.equal(meta.wordpress_draft_id,101); assert.equal(meta.status,'draft'); assert.equal(sha256(html), sha256(post.content.raw)); } finally {await srv.close()}});

test('duplicate slug stops before create', async()=>{const {root}=fixture(); let created=false; const srv=await server((req,res)=>{if(req.url.startsWith('/wp-json/wp/v2/users/me')) return json(res,{id:1}); if(req.url.includes('slug=demo')) return json(res,[{id:9,slug:'demo',status:'draft',title:{raw:'Other'},content:{raw:'x'}}]); if(req.url==='/wp-json/wp/v2/posts'){created=true} json(res,[])}); try{await assert.rejects(stagedPost({slug:'demo',root,baseUrl:srv.url,username:'u',password:'p'}),/Manual confirmation/); assert.equal(created,false)} finally {await srv.close()}});

test('duplicate title stops before create', async()=>{const {root}=fixture(); const srv=await server((req,res)=>{if(req.url.startsWith('/wp-json/wp/v2/users/me')) return json(res,{id:1}); if(req.url.includes('status=draft')) return json(res,[{id:8,slug:'other',status:'draft',title:{raw:'Demo Title'},content:{raw:'x'}}]); json(res,[])}); try{await assert.rejects(stagedPost({slug:'demo',root,baseUrl:srv.url,username:'u',password:'p'}),/Manual confirmation/)} finally {await srv.close()}});

test('metadata id matching remote content is idempotent', async()=>{const {root,html}=fixture(); fs.writeFileSync(path.join(root,'articles','demo','metadata.json'),JSON.stringify({title:'Demo Title',slug:'demo',wordpress_draft_id:7})); let posts=0; const srv=await server((req,res)=>{if(req.url.startsWith('/wp-json/wp/v2/users/me')) return json(res,{id:1}); if(req.url.includes('/posts/7')) return json(res,{id:7,slug:'demo',status:'draft',title:{raw:'Demo Title'},content:{raw:html}}); if(req.method==='POST') posts++; json(res,[])}); try{const r=await stagedPost({slug:'demo',root,baseUrl:srv.url,username:'u',password:'p'}); assert.equal(r.action,'already-matches'); assert.equal(posts,0)} finally {await srv.close()}});

test('minimal create timeout recovers staged draft without reposting', async()=>{const {root,html}=fixture(); let createCount=0; let searchingAfterTimeout=false; const hash=sha256(html); const srv=await server((req,res,body)=>{if(req.url.startsWith('/wp-json/wp/v2/users/me')) return json(res,{id:1}); if(req.url==='/wp-json/wp/v2/posts'&&req.method==='POST'){createCount++; searchingAfterTimeout=true; req.socket.destroy(); return} if(req.url.startsWith('/wp-json/wp/v2/posts?')) return json(res, searchingAfterTimeout ? [{id:12,slug:'demo',status:'draft',title:{raw:'Demo Title'},content:{raw:`<!-- codex-staged-draft content-sha256="${hash}" -->`}}] : []); if(req.url==='/wp-json/wp/v2/posts/12'&&req.method==='POST') return json(res,{id:12,slug:'demo',status:'draft',title:{raw:'Demo Title'},content:{raw:JSON.parse(body).content}}); if(req.url==='/wp-json/wp/v2/posts/12?context=edit') return json(res,{id:12,slug:'demo',status:'draft',title:{raw:'Demo Title'},content:{raw:html}}); json(res,[])}); try{await assert.rejects(stagedPost({slug:'demo',root,baseUrl:srv.url,username:'u',password:'p'})); assert.equal(createCount,1)} finally {await srv.close()}});

test('forbids non-draft status and local-only does not require WordPress', async()=>{assert.throws(()=>parseArgs(['--slug','demo','--status','publish']),/Only draft/); const {root}=fixture(); const r=await stagedPost({slug:'demo',root,localOnly:true}); assert.equal(r.action,'local-only')});

test('lock prevents same slug start and secrets are sanitized', async()=>{const {root}=fixture(); fs.mkdirSync(path.join(root,'.wp-draft-locks')); fs.writeFileSync(path.join(root,'.wp-draft-locks','demo.lock'),'x'); await assert.rejects(stagedPost({slug:'demo',root,baseUrl:'http://example.invalid',username:'secret-user',password:'secret-pass'}),/Lock exists/)});
